### ISSUE TITLE
TODO: Indexer Implementation Specifics

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#12]
"Write an index."

**Comment by 0xAlmir** [comment]
I'd also like to add in on this.
If it's possible to either make APIs public or make the Indexer front-end use **Client-Side Rendering** because as we've seen scrapers drag the page loading times down a lot on the ordinals.com page since it uses SSR which returns essentially a lot of useless data for scrapers.

**Comment by Psifour** [comment]
Due to it's nature as a fungible token protocol, I support the API endpoints being a target. I think that a good development interface will far exceed the value of a frontend as every service that chooses to work with these will have their own existing UI/UX that they want to integrate it with. This also shortens the development cycle for some of these products/services.

**Comment by casey** [comment]
I do actually think that a canonical, human-readable front-end is probably more important, initially, than an API. APIs area great for building services and products, but what's needed to reify this thing is a source of truth that people can look at, which means an index with a website front end, that people can run and look at. An API is still super important though, just speaking for where my priorities lie.

**Comment by casey** [comment]
A basic and index has been merged into `ord`. Closing this in favor of more specific issues.
