### ISSUE TITLE
Rune: Max supply

### ISSUE THREAD

**Issue by lugondev** [casey/runestone#143]
Currently, I only see the limits on the deadline (timestamp) and term (number of blocks). I think we should add a supply limit. When one of these three limits is reached, the rune claiming process will be stopped.

**Comment by lugondev** [comment]
I think it may be called hard_cap of rune.

**Comment by casey** [comment]
This is not possible, due to the desire for runes to support an SPV-like mode where only a subset of transactions need to be downloaded to validate a given rune transaction. A hard-cap on supply of runes for an open etching would require, for a given transaction, wallets to download all transactions in all blocks between the beginning and end of the open etching, in order to validate whether or not the original etching was valid.

**Comment by lugondev** [comment]
When I claim runes after they're etched, I notice the "mints" increase. In my view, we can increase the current_cap after minting. And we compare current_cap to hard_cap in the same way we compare timestamps or term blocks.

**Comment by lugondev** [comment]
Please help me clarify this issue, thank you @casey.

**Comment by casey** [comment]
`ord` can do this, but only because `ord` sees every transaction. If a light wallet is processing a subset of transactions, it can't track mints or current cap.
