### ISSUE TITLE
Bonding curves

### ISSUE THREAD

**Issue by casey** [casey/runestone#145]
This would be an extension of #58. Make it possible to offer a variable exchange rate, that increases as more runes are purchaes.

**Comment by mcbagz** [comment]
While that type of bonding curve makes sense for a market maker, I have actually been conceptualizing the opposite desire for an individual seller. For example:
- I have 1000 runes, and I would like to sell them all. 
- I would accept the current going rate and take 1 BTC/100 runes. 
- However, if someone would buy them all at once, I would be willing to take 9.5 BTC for the whole stack. 
- Instead of having to manage a lot of smaller sales, I would be willing to part with the total at a discount.

Also, any progressively increasing price will simply be undercut by people selling similar amounts at fixed prices, as long as both options are available. Replicating a system like Uniswap makes sense if the particular offer can be used repeatedly/indefinitely, and correct me if I'm wrong, but my understanding is that they are single use.

Edit: I suppose my point in this is: why? Is this a desired feature? I'm sure people would create clever uses out of any feature that is available, but that's not a good motivation to simply add more features.

**Comment by afeezaziz** [comment]
this basically can create an amm?

**Comment by casey** [comment]
Sort of. It's basically equivalent to an AMM, but with a single liquidity provider, with some rate limits of how often it can be interacted with, since each interaction consumes and produces a new UTXO.

**Comment by Nifty2881** [comment]
This is making sense.

**Comment by sondotpin** [comment]
Will logic of this feature added to core of Protocol? or put the logic outside?

**Comment by casey** [comment]
This would be part of the protocol.

**Comment by johnquid** [comment]
> This would be part of the protocol.

Do you see extensions to the logic, like leveraging the AMM to lend and borrow, as forks of Rune??

**Comment by casey** [comment]
I think this is very far into the future, and I'm not sure this is the best way to support variable offers. My current line of thought is that, on bitcoin, the best way to have liquidity pools and AMMs, is actually to have online nodes which can collaboratively construct atomic swap transactions with any terms. I'm thinking of calling this approach "light pools". Look forward to a blog post!
