### ISSUE TITLE
support stablecoins

### ISSUE THREAD

**Issue by buddh0** [casey/runestone#146]
Most of the FTs on Bitcoin are garbage, with stablecoins being the exception. However, stablecoins require the ability to limit the issuer and open up the issuance time window. Is it possible for Runes to support this?

**Comment by casey** [comment]
When a rune is etched, the creator can specify that it is not an open mint, and allocate the entire supply to themselves. For later issuance, the creator can mint a very large number of runes, and put it in cold storage, and transfer runes out of cold storage in order to issue more of the stablecoin.
