### ISSUE TITLE
Expands Open etching

### ISSUE THREAD

**Issue by sondotpin** [casey/runestone#165]
- [ ] An open etching does not have the ability to allow the owner to premint a certain amount (exceeding the limit). This limits the ability to create a suitable Rune economics for degens

- [ ] It is also possible to create a Rune with 2 rounds of open etching with different limits and terms

**Comment by casey** [comment]
> * [ ]  An open etching does not have the ability to allow the owner to premint a certain amount (exceeding the limit). This limits the ability to create a suitable Rune economics for degens

See #124. I'm planning on relaxing this, and allowing the initial etching to allocate any amount, including above the limit, but if this is done it will be displayed prominently on the rune's info page.

> * [ ]  It is also possible to create a Rune with 2 rounds of open etching with different limits and terms

I don't want to do this because a rune doesn't have an "owner" in any sense. There isn't an address or public key attached to the etching which has special privileges. However, you can create an inscription when creating a rune, and then later use that inscription to create a new rune under it, and you can give meaning to that, i.e., that the two runes represent the same asset.

You can also premine a bunch and use some other allocation mechanism. Ideally CTV is activated, which would allow trusted airdops and open etchings without any explicit support from the protocol.

**Comment by HubertusVIE** [comment]
Aren't airdrops always connected with fraud and scams? Why would we want them on Bitcoin? IMHO ownership, right from the etching, is fundamental for an honest system of specialised digital assets.

**Comment by casey** [comment]
> Aren't airdrops always connected with fraud and scams? Why would we want them on Bitcoin? IMHO ownership, right from the etching, is fundamental for an honest system of specialised digital assets.

I'm not being prescriptive about whether or not airdrops are good, I'm just commenting that if you want to do an airdrop, there are extra-protocol methods to do so, which are better than baking support into the protocol.

**Comment by HubertusVIE** [comment]
> There isn't an address or public key attached to the etching which has special privileges. However,

That's what I was referring to: "no owner". Will there be a possibility for a call to ask questions about the inscription workaround?  I am looking for the best way to have a specialised digital asset on Bitcoin mainchain, similar to the IMF's SDRs, just without any attack vector from governments. Considering Runes instead of TA.
