### ISSUE TITLE
IDEA: ADD INSCRIPTION TXID REF

### ISSUE THREAD

**Issue by stet** [casey/runestone#17]
RUNE is outside of Ordinals. 
Add standard (could be additional tx output) to point to an inscription ID.
This allows easy association with broader Bitcoin content such as image, full metadata, contracts, anything.

**Comment by summraznboi** [comment]
I think metadata should be kept separate, and instead be some JSON inscription blob format can be inscribed in the same transaction as the issuance to provide the metadata.

**Comment by stet** [comment]
Yes but also see my comment on using "rune" not "ord" if so 
#18 
[18#issuecomment-1738223925](https://github.com/casey/runestone/issues/18#issuecomment-1738223925)

**Comment by casey** [comment]
There are two approaches here:

- A rune may reference an inscription by ID
- A rune issuance transaction may also be an inscription transaction

I think I favor the latter.

**Comment by Psifour** [comment]
> A rune issuance transaction may also be an inscription transaction

We can enable that with a method like I recommended here https://github.com/casey/runestone/issues/18#issuecomment-1738241202 _without_ including any direct assertions of structure to this data. This further satisfies the users request (unstructured means application-specific structures can arise without complicating Runestone), is compatible with it being a reveal transaction, and avoid inclusion of references to Ordinals in Runestone (due to being different at almost every level UTXOvsOrdinals, FTvsDataStorage, etc.)

**Comment by casey** [comment]
Done. If the transaction etching a rune also reveals an inscription, the /rune page links to that inscription.
