### ISSUE TITLE
Inscription metadata in rune deploy.

### ISSUE THREAD

**Issue by elocremarc** [casey/runestone#18]
What if there was a way to do a inscription when a rune is deployed. You could inscribe the rune logo and additional metadata when a rune is created.

**Comment by stet** [comment]
I think part of the goal with RUNE is to offload token related inscriptions.
This might encourage additional JSON metadata so if this is supported, maybe force a "rune" protocol specifier.

**Comment by summraznboi** [comment]
That’s too complicated to start IMO, we should wait and see how the community would handle metadata with existing ordinals infra first before considering another inscription envelope type. Simple and not over engineering is best especially for a fungible payment protocol.

**Comment by Psifour** [comment]
> Simple and not over engineering is best

Concept ACK :laughing: 

Kidding aside, keeping the protocol tight should definitely be a priority, but allowing for future protocol development without colliding with application specific or user-driven development would be a definite `nice to have`

As a "top of mind" solution I would say we could do

OP_RETURN
**Transfers Push**
**Issuance Push**
**Protocol Push**
**User Data Push**

Protocol push being reserved for protocol specific improvements/expansion and strictly defined as block height activated changes where all non-defined values are strictly rejected, making 0x00 the only valid op for it currently as there would be no valid options other than an empty push.

User data push would be unstructured and purposefully not validated by Runestone (except in so much as Runestone allows it to exist without invalidating the protocol message as a whole).


This let's us kick the can down the road without creating the same collision of concerns as we have in ord due to having a strict list of allowed values for protocol pushes and not caring about the content of the user data push.

**Comment by summraznboi** [comment]
> User data push would be unstructured and purposefully not validated by Runestone (except in so much as Runestone allows it to exist without invalidating the protocol message as a whole).

I like this approach, and probably in the future when we do want to support a protocol push, the first varint in the protocol represent the protocol version starting with 0, so that we can continuously update protocol extensions (similar to segwit versions). Also, we can allow for skipping over the issuance push with a 0x00 op, so that protocol and/or user data push can be accessed without the need for issuance.

**Comment by stet** [comment]
> That’s too complicated to start IMO, we should wait and see how the community would handle metadata with existing ordinals infra first before considering another inscription envelope type. Simple and not over engineering is best especially for a fungible payment protocol.

Not a new envelope type, simply don't use "ord" otherwise we will just see prob JSON metadata inscriptions flood ord in addition to BRC-20, which is not ideal imo.

**Comment by jerryfane** [comment]
> User data push would be unstructured and purposefully not validated by Runestone (except in so much as Runestone allows it to exist without invalidating the protocol message as a whole).
> 
> 
> 
> 
> 
> This let's us kick the can down the road without creating the same collision of concerns as we have in ord due to having a strict list of allowed values for protocol pushes and not caring about the content of the user data push.


I'm in favor of the idea of users pushing optional data. One suggestion is to push an inscription ID that references a JSON, like:

```javascript
{
    "p": "runestone",
    "symbol": "RUNE",
    "logo": "<inscription_id>",
    ...
}
```

This would be purely for clients and indexers to easily retrieve metadata.

**Comment by elocremarc** [comment]
> I'm in favor of the idea of users pushing optional data. One suggestion is to push an inscription ID that references a JSON, like:

> Not a new envelope type, simply don't use "ord" otherwise we will just see prob JSON metadata inscriptions flood ord in addition to BRC-20, which is not ideal imo.

It would make more sense to use an inscription image reference that ID for the logo and then add metadata fields to that once metadata gets merged in ord for all the rest of the stuff.  Could also use the metaprotocol field to specify its a rune metadata. --metaprotocol runemeta
https://github.com/ordinals/ord/pull/2421
https://github.com/ordinals/ord/pull/2449

**Comment by Psifour** [comment]
I am strongly opposed to creating strong interconnections at the protocol level between runes and ord as they do not use any shared underlying tech (other than Bitcoin itself). One is UTXO-based with OP_RETURNs, the other is Ordinal-based with witness data.

If we are referencing the inscription(s) in user-data pushes whose content is not explicitly defined in the spec/protocol, then I very much like these ideas (especially eloc's comments about using metadata in envelope). This facilitates users to develop their own meta-protocol layer of interconnections to various other services (ord in this case), without the need for the protocol directly weighing in on what should be heavily-opinionated application-specific decisions.

**Comment by stet** [comment]
I think Non-transferrable Artifacts (NTA) aka soul-bound tokens should be considered as contextually relevant here. 

Ideally, a RUNE deploy pointing to some inscription(s) should not be inherently _movable_ as per Ordinal Theory.
 
This is why I mention using a different protocol identifier if an inscription is part of a RUNE deploy TX. If not and point to existing inscription (within ord) then it is more acceptable since repurposes content such as a so-called ticker or logo. Still would be odd to be able to _sell_ part of a RUNE object due to ord reference. Could always send ord inscription to burn address though. Overthinking perhaps. It's all wonky eod.

**Comment by jerryfane** [comment]
> I think Non-transferrable Artifacts (NTA) aka soul-bound tokens should be considered as contextually relevant here.
> 
> Ideally, a RUNE deploy pointing to some inscription(s) should not be inherently _movable_ as per Ordinal Theory.


Why? What's the issue in transferring a RUNE deploy metadata? As long as inscription ID is constant, we should be good.

**Comment by stet** [comment]
> Why? What's the issue in transferring a RUNE deploy metadata? As long as inscription ID is constant, we should be good.

"Ideally" because it is wonky. Just something to think about at minimum. Normally, the metadata assets a token points to are not themselves tradable assets independent from the tokens. It is why BRC-20 inscriptions don't need Ordinal Theory except in cases where total supply is reserved and token never used (token deploy inscription + all tokens can be sold to new owner). 

RUNEs does not need Ordinal Theory, but it still could make use of inscription envelopes, which are not inherently Ord specific. 

This is more of a devil's advocate remark, since I have also suggested leveraging Ord inscriptions for tickers and metadata as well. There is nothing stopping people to add an inscription pointer (reveal TXID) if there is space allocated for it. But combining RUNE deploy with an Ord inscription in same TX would encourage Ord namespace use when it could just as easy be a new envelope protocol specifier (as a NTA envelope). 

Either way, nobody will lose sleep over it. Just a fellow technologist injecting broad view design opinions.

**Comment by casey** [comment]
This is done. When you etch a rune, if the same transaction reveals an inscription, the inscription is displayed on the /rune page. The meaning of such an inscription, e.g., if it is just metadata, or if the inscription itself represents the issuer and its transfer has meaning, is an open question.
