### ISSUE TITLE
AMM infrastructure design

### ISSUE THREAD

**Issue by sondotpin** [casey/runestone#21]
Could you please think about this @casey 

- [ ] Approve function
- [ ] Logic of an AMM

**Comment by AmethystWizard** [comment]
pee pee poo poo

**Comment by casey** [comment]
I haven't thought about this, but can't it just be done with a bunch of PSBTs?

**Comment by casey** [comment]
Maybe we could support this with some kind of weird-ass output index. The output index is encoded as a u128 bit VLQ varint. However, the number of outputs is usually small, certainly less than a few thousand, so there are a lot of invalid output values that we could play with.

One idea is that sellers of runes could include a transfer directive which was something like `[ID, AMOUNT, OUTPUT]`, where `OUTPUT` is some special value that this indicates that it's an offer, and `AMOUNT` is actually an exchange rate.

Then, the input values determine how the amount of that token is distributed, which would allow a sort of offer PSBT to be created, where you can accept it and pay any amount of BTC, with the amount of BTC that you pay determining the amount of the token that you receive. Pretty fucked up, but it avoids the issue of having to generate a PSBT for every lot size.

**Comment by summraznboi** [comment]
After a lot of thought, I think I have come up with a viable way to make this work. The hardest part is to figure out a way to signal "the amount of BTC that you pay", since it is not immediately clear which transaction outputs is considered a valid payment. A solution is to say all UTXOs addressed to the same address as the input that share the same index as the OP_RETURN runestone output counts as payment. But what if the seller wishes to receive payment with another address? There isn't a good way to handle that given there isn't currently a SIGHASH type that allows for signing for an arbitrary set of inputs/outputs.

However, if we consider an extension for a protocol push as mentioned at https://github.com/casey/runestone/issues/18#issuecomment-1738241202, then the desired scriptPubKey can be encoded here.

**Comment by T1-O** [comment]
AMM works quite well because its interactive. Its literally an automatic market maker, as in automatically quoting a price for the underlying assets, Runes in this case. Not sure how this can be achieved with UTXOs and OP_RETURNs.

Apart from that it adjusts future quotes automatically by interpreting demand from the latest exchange.
Thats a lot of logic to fit into limited bytes. This sounds like a layer2 task to calculate and make the next quote available.

**Comment by Psifour** [comment]
I would agree with T1 that attempting to include this directly in Runestone is probably excessive, but I do support including features (where able) to facilitate other's making tools/services around it.

In this case this sounds like the sort of problem where the majority of the changes/work should happen externally (OP_VAULT/CTV) with support for small data inclusion happening on this end if needed to support those efforts.

**Comment by casey** [comment]
Closing in favor of #58. We probably won't have AMMs, but we can maybe do variable offers.
