### ISSUE TITLE
Build a community around Runestone

### ISSUE THREAD

**Issue by lopezi** [casey/runestone#22]

**Comment by Psifour** [comment]
Due to the nature of both services having rather exploitable designs, I would be very wary of joining a server/GC that didn't have the explicit support and validation by people I trust within the community.

There are a few such chats, but this is the first one I've seen advertise through the Github.

**Comment by casey** [comment]
You're free to create whatever discord and telegram groups you want. However, they are not associated with this project and shouldn't be advertised here.
