### ISSUE TITLE
Thoughts on Future Soft Forks vs Hard Forks

### ISSUE THREAD

**Issue by owenstrevor** [casey/runestone#28]
Curious if you have any thoughts on how Runestone could be upgraded in the future, and if there's a way to make it more likely that a great universe of things will be soft forks rather than hard forks.

**Comment by casey** [comment]
Runes are simple enough that my naïve hope is that it never needs upgrades.

**Comment by Psifour** [comment]
> Curious if you have any thoughts on how Runestone could be upgraded in the future, and if there's a way to make it more likely that a great universe of things will be soft forks rather than hard forks.

I proposed a solution in #18 that leaves room for future development without placing any of that burden on this implementation.

**Comment by casey** [comment]
Here's a proposal for soft forks:

- We figure out which when a runestone is invalid.
- These include ID zero when there's no issuance symbol and decimal, since ID zero can only be used in an issuance transactions.
- IDs equal to or greater than 2^64, since there will never be that many IDs
- An amount which is greater than the amount of runes available to allocate in that transaction.
- Payloads which don't deserialize correctly.
- Invalid output IDs greater than the maximum valid output ID for that transaction.

An un-upgraded indexer, upon encountering a transaction with any of the above, burns *all* runes that are input to that transaction.

An upgraded indexer can give some other meaning to these ranges of invalidity, and assign the runes input to that transaction according to new rules.

I think kind of similar to what @Psifour proposes in #18.

As a note, I want to have the payload be the concatination of all data pushes after the sentinal value. Data pushes are limited to 520 bytes, so if we give specific meaning to multiple data pushes (e.g., first data push is transfers, second data push is issuance, etc) we then run into the problem of how to deal with scenarios where one of these segments is greater than 520 bytes.

**Comment by casey** [comment]
Figured this out in #51.
