### ISSUE TITLE
TODO: Determine Protocol Feasibility

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#3]
"Decide whether or not I should do this at all. Fungible tokens are almost entirely meritless. However, alternative fungible token standards, like BRC-20, have a large on-chain footprint and have lead to a proliferation of UTXOs, and standards with no on-chain footprint have UX challenges and have been slow to see adoption."

**Comment by casey** [comment]
There are two issues here as I see it:

One is personal motivation. I might decide that this is all just a horrible waste of time. However, it's all open source code, and whatever I do will likely have some value. Any motivated individuals can just pick things up from where I leave them.

The other is related to alternative protocols. I think that Taproot Assets and RGB are better than runes in many ways. Transactions can be kept confidential, and there is less on-chain footprint. However, there are a couple factors which make me worry that both protocols won't see significant adoption.

One of these factors is complexity. Taproot Assets and RGB are both fairly complex protocols to implement. This might limit the proliferation of compatible services which seem to have helped a lot with adoption of ordinals.

The other factor is UX complexity which comes from the fact that both protocols rely on off-chain data. This means that in order to perform transactions, users need to run their own server, rely on someone else's server, or use some kind of P2P network for the exchange of this off-chain data. I worry a bit that this might limit adoption, and and make it unappealing for end users.

**Comment by Psifour** [comment]
That is an astoundingly direct assessment of the drawbacks of both of those existing token protocols.

**Comment by summraznboi** [comment]
Word :)

**Comment by BitTogether** [comment]
Maybe a "price check" on features like mint and transfer would be a good way to compare financial feasibilities? Price of mint, price of transfer, price of airdrop to 1-10-100 users.  I understand this will change as the size of transactions changes during development, but it might offer a baseline to compare with other protocols.  
edit: We also need to access the feasibility of getting miners to pick up our out of spec stuff and what might they charge us to do it?

**Comment by afeezaziz** [comment]
> There are two issues here as I see it:
> 
> One is personal motivation. I might decide that this is all just a horrible waste of time. However, it's all open source code, and whatever I do will likely have some value. Any motivated individuals can just pick things up from where I leave them.
> 
> The other is related to alternative protocols. I think that Taproot Assets and RGB are better than runes in many ways. Transactions can be kept confidential, and there is less on-chain footprint. However, there are a couple factors which make me worry that both protocols won't see significant adoption.
> 
> One of these factors is complexity. Taproot Assets and RGB are both fairly complex protocols to implement. This might limit the proliferation of compatible services which seem to have helped a lot with adoption of ordinals.
> 
> The other factor is UX complexity which comes from the fact that both protocols rely on off-chain data. This means that in order to perform transactions, users need to run their own server, rely on someone else's server, or use some kind of P2P network for the exchange of this off-chain data. I worry a bit that this might limit adoption, and and make it unappealing for end users.

With regards to Taproot and RGB, id love to learn more, but googling only giving me blog posts which have no technical discussions. Where should I find more about this?

**Comment by casey** [comment]
I'm having fun implementing, and I'm enjoying crafting the greatest shitcoin carnival the world has ever seen, so it's probably feasible.

**Comment by cbspears** [comment]
Godspeed

**Comment by bluezdot** [comment]
Word
