### ISSUE TITLE
Figure out how PSBTs work

### ISSUE THREAD

**Issue by casey** [casey/runestone#46]
Offering runes for sale via PSBT should be quite simple.

First, the seller transfers the runes for sale to output `RUNE_INPUT`. They then sign for `RUNE_INPUT` using `SIGHASH_SINGLE | ANYONECANPAY` committing to an output `BTC_OUTPUT` paying themselves the sale price.

The buyer then completes the transaction by supplying an input for the sale price, `BTC_INPUT`, along with an output to receive the runes, `RUNE_OUTPUT`.

The buyer puts their input and output first. Since the completed transaction has no runestone, all input runes transfer to to the first output, `RUNE_OUTPUT`.

The completed transaction looks like:

```
BTC_INPUT  | RUNE_OUTPUT
RUNE_INPUT | BTC_OUTPUT
```

**Comment by casey** [comment]
I'm trying to figure out a more complex arrangement where a seller can put up some amount of runes, along with a BTC/rune exchange rate, and the buyer can supply a variable amount of BTC, and receive the corresponding amount of runes, but it's pretty tricky.

**Comment by casey** [comment]
You would need to commit to an input, a change output for un-purchased runes to get sent back to, and an OP_RETURN containing the runestone specifying the exchange rate. The buyer would then need to supply an additional input and two outputs.

However, there isn't a combination of sighash flags that let you commit to one input and two outputs, while still allowing the additional input and outputs to be added.

**Comment by basecoin20** [comment]
> I'm trying to figure out a more complex arrangement where a seller can put up some amount of runes, along with a BTC/rune exchange rate, and the buyer can supply a variable amount of BTC, and receive the corresponding amount of runes, but it's pretty tricky.

Purchase in designated quantities This is a difficult problem but it is important

**Comment by BennyTheDev** [comment]
wait, can't the seller sign as 3rd party, specifying the change in an op_return (or the output of signer 3 being for change if it's the same as the seller)? I couldn't find no info that would suggest signers must be unique across a psbt.

**Comment by casey** [comment]
> wait, can't the seller sign as 3rd party, specifying the change in an op_return (or the output of signer 3 being for change if it's the same as the seller)? I couldn't find no info that would suggest signers must be unique across a psbt.

Can you be more specific? I'm not sure I understand what you're getting at.

**Comment by casey** [comment]
If you're talking about the more case of selling a variable amount of runes, depending on a specified exchange rate, or selling some of the runes in a UTXO, I haven't figured out a way to do that.

**Comment by summraznboi** [comment]
I haven't put much thought to it, but what if we relax the runestone from only being found in OP_RETURN outputs to any input or output? We can have the envelope be either starting with OP_RETURN or OP_0 OP_IF ... OP_ENDIF, and then the seller can just have one input/one output, where the runestone is located in the input as part of the reveal.

**Comment by T1-O** [comment]
> 
> ```
> BTC_INPUT  | RUNE_OUTPUT
> RUNE_INPUT | BTC_OUTPUT
> ```

Thats very similar to how ordinal transfers work. What about padding/dummy outputs for small amounts(500 or 600 sats) that we see for ordinal transfers, do you see rune transfers  needing the same or something similar?

**Comment by casey** [comment]
> I haven't put much thought to it, but what if we relax the runestone from only being found in OP_RETURN outputs to any input or output? We can have the envelope be either starting with OP_RETURN or OP_0 OP_IF ... OP_ENDIF, and then the seller can just have one input/one output, where the runestone is located in the input as part of the reveal.

I don't think this solves the problem. What we want is for a seller with a UTXO containing a bunch of runes to be able to make an offer for *some* of these runes, without having to first split them off with a new transaction. If the seller can split off the runes for sale, then we can just use the simple two-input/two-output case.

If we put the runestone in the inputs, in an envelope, then the seller would first have to create a transaction to commit to the input runestone, and then the buyer could accept in a second transaction. So ignoring some other problems, we could put the runestone in an input, but that would still require an additional transaction.

**Comment by summraznboi** [comment]
> I don't think this solves the problem. What we want is for a seller with a UTXO containing a bunch of runes to be able to make an offer for some of these runes, without having to first split them off with a new transaction. If the seller can split off the runes for sale, then we can just use the simple two-input/two-output case.

**Comment by summraznboi** [comment]
> If we put the runestone in the inputs, in an envelope, then the seller would first have to create a transaction to commit to the input runestone, and then the buyer could accept in a second transaction. So ignoring some other problems, we could put the runestone in an input, but that would still require an additional transaction.

You are right, runestone as part of an input script reveal does require a preceding transaction that commits to it. However, this scheme does allow for a noninteractive sell with exchange rate with only 2 psbt signatures from buyer and 1 from buyer. Note that while the seller does pay for first transaction’s gas fee, the seller can just have it be the minimum of 1 sat/vbyte and the buyer would be motivated to supply enough gas for both transactions. The trick here is that you would only broadcast both transactions at the same time once a buyer decides to perform the order. This does require the seller to trust the marketplace to not broadcast the first transaction before the second is finalized, which makes this a somewhat trusted scenario.

Another wacky thought I had was to actually support “rune pebble” in the nsequence field of an input. It would only support one transfer operation, and only handle the runes in the specific input. Then by disabling the relative timelock, we have 31 bits of usable bits, which is enough to encode information if we use shortcuts (such as the ordinal position of the rune ID relative to all other IDs in the input, using some vardecimal encoding for amount like 14 bits mantissa and 6 bits power of 10 exponent, etc). This does add complexity since it’s a set of different encodings compared to output runestones, but might be the key to giving us more flexibility around the SIGHASH_SINGLE signature limitation.

Exponent specifies unsigned number from 0 to 63, and we offset by 40 to get -40 to 23. Then a rune's max possible supply is 2^128 ≈ 3.4e38, so we have flexibility to state total max rune supply of 2^128 being worth 1 sat to 1 rune being worth all 21 million bitcoin (2.1e15 sats). Mantissa uses 14 bits, which supports 0 to (2^14 - 1) = 16383, or just enough for 4 decimal digits. Combined is 20 bits, which leaves an ample 11 bits to indicate rune ID and operation. We could simplify even more and assume to only ever work on the lowest rune ID, which would encourage people to hold different runes in different UTXOs for maximal flexibility.

**Comment by casey** [comment]
Closing this, since simple transfers are easy. Opened #58 to track variable transfers.
