### ISSUE TITLE
Restrict Minimum Symbol Length

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#7]
"Decide if symbols should be restricted to be no longer than the most recently mined sat name."

**Comment by summraznboi** [comment]
This is only useful if we want to keep unique symbols, it could also be interesting to restrict symbol to the set of sat names burned into the OP_RETURN, that's an unambiguous way of enforcing uniqueness of symbol name, and driving secondary demand of sats for nice-sounding sat names.

**Comment by Psifour** [comment]
I love the idea of the tight correlation, but I err on allowing duplicate symbols which undermines my ability to support this. This also keeps these two systems separate which avoids dependency on Ordinal Theory (which is amazing, but comes with indexing requirements).

**Comment by casey** [comment]
Figuring out the most recently mined sat is easy enough, since it depends only on the block height. The real question is how would degens feel about 11+ character ticker symbols, and 10 character symbols only slowly becoming available between November, 2023, and October, 2042.

**Comment by bitspill** [comment]
I don't believe the degen community would readily get behind 10-11+ character symbols in the same way they would 3-4char for a few reasons

- similar to domains, short and easily pronounced/spelled is easier to communicate without error/typo 
- without casing it will be a difficult to read string of only uppercase letters
- convention paralleling stock/forex markets with symbols in the 1-4 char range
- UI/UX will be more complicated rendering 10-11 char symbols in websites or wallet apps


Some examples:
`Balance: 123 ABCDEFGHIJK` vs `Balance: 123 ABCD`

`Can you send me 10 ABCDEFGHIJK`

| symbol      | txid          | date       | amount |
|-------------|---------------|------------|--------|
| ABCDEFGHIJK | 0xdead...beef | 2023.10.02 | 100    |
| LMNOPQRSTUV | 0xdead...beef | 2023.10.02 | -10    |
| ABCDEFGHIJK | 0xdead...beef | 2023.10.02 | 25     |
| LMNOPQRSTUV | 0xdead...beef | 2023.10.02 | 32     |
| LMNPPQRSTUV | 0xdead...beef | 2023.10.02 | 14     |
| ABCDEFGHIJK | 0xdead...beef | 2023.10.02 | -100   |

| symbol | txid          | date       | amount |
|--------|---------------|------------|--------|
| ABCD   | 0xdead...beef | 2023.10.02 | 100    |
| LMNO   | 0xdead...beef | 2023.10.02 | -10    |
| ABCD   | 0xdead...beef | 2023.10.02 | 25     |
| LMNO   | 0xdead...beef | 2023.10.02 | 32     |
| LMNP   | 0xdead...beef | 2023.10.02 | 14     |
| ABCD   | 0xdead...beef | 2023.10.02 | -100   |

Did you notice the 2nd to last replaced O with P? It's much easier to see on the shorter symbol. If a user is expecting to receive LMNOPQRSTUV a malicious actor may attempt to sneak a look alike in hopes the recipient doesn't catch it and believes they've been paid
 -- caveat this look alike protection relies upon unique symbols; if duplicates are allowed then there has to be another discussion on how to expose the token ID in a productive manner

**Comment by decentralizd** [comment]
I'm fairly sure none of you guys actually buy altcoins and are just throwing "cool sounding" things at the wall to help you feel like you're not creating a shitcoin machine, but any form of uniqueness is tickers is most definitely not a good thing.

- You lose the ability to reuse tickers some moron is squatting, and/or chose a horrible supply etc
- Stuck with supply of said moron if you "buy it out" (if at all possible, likely not)
- What about v2 tokens requiring the same ticker as the v1?
- I can front run any project now, hijacking their tickers for fun.
- Complexity is not good if your goal is to allow people to use Bitcoin over ETH in this situation. ETH already makes it 1000x easier and likely will continue.
- Makes BRC20 more likely to survive long term vs the Runes protocol, which I am sure is not Casey's goal.
- Someone will instantly fork Runes and add non unique tickers. 
- Pepe:1, Pepe:2, Pepe:3 is also basically unique tickers and a fairly cringe suggestion imo. 
- Ticker length is not an issue, people ape extremely long tickers all day long. 
- If you want users, don't make the UX complicated. Don't make the system hard to comprehend. Do not try to reinvent the wheel in some "special bitcoin" way. It's a waste of time. Make a tool that allows people to efficiently launch tokens on Bitcoin. That's it. The rest is just dev ego wanting to do something quirky, it won't work.

Source: been shitcoining since Darkcoin

Happy this is an open discussion for what it's worth, even if you guys ignore me and go based off your minimal shitcoin experiences.

Thanks!

edit: whoops should I post this elsewhere? Didnt realize it was on a specific length discussion, my bad.

**Comment by Psifour** [comment]
> edit: whoops should I post this elsewhere? Didnt realize it was on a specific length discussion, my bad.

It came across as applying to this discussion. Did you actually mean to comment on #5?
I think we largely agree, as I mentioned above (https://github.com/casey/runestone/issues/7#issuecomment-1738260578), that allowing duplicate symbols mitigates/eliminates the need to dabble with any sort of length-based restriction.

**Comment by casey** [comment]
One issue with defining a fixed price to mint a rune, e.g., an amount of bitcoin to burn, is that might be too high or too low, depending on the price of bitcoin. One option would be to define a fixed price, but one which falls over time. This ensures that even if the price is too high, it will eventually fall to a good value. If it decays to zero, it will eventually be too low, but that isn't an issue if short runes have been etched by then, i.e., it will have served its purpose. So, we could start with some initial price schedule, with shorter runes requiring more bitcoin burned, and then decrease it by half, maybe every halving, although that might be too slow.

**Comment by casey** [comment]
Here are the options as I see them:

- Restrict minimum rune length, with shorter runes being allowed over time. E.g., allow twelve character and above runes can be etched immediately, with the minimum dropping by one every X blocks.
- Restrict minimum rune length by burn. Shorter symbols require burning more bitcoin. Amount required decays over time, until zero.

Allowing shorter runes over time, with no burn, has some undesirable properties. Each time the minimum length gets shorter, there's a PVP mempool rush to mint the shorter symbols. Additionally, it introduces MEV, since miners can just put their transactions earlier in the block to receive the newly unlocked symbols.

Allowing by decaying burn does lead to some rush, each time the price decays. However, if the decay is gradual, it should be small. It introduces less MEV, since miners still have to burn BTC. It does suck if you burn BTC and don't wind up getting the symbol.

**Comment by summraznboi** [comment]
What if we do keep the burn, but rather burning just regular sats, we require burning of rare sats? And each symbol length has its own decay schedule, with starting from 1 mythic as the practical block of purchaseable ability until price starts to decay to legendary/epic/rare/uncommons.

This does depend on rare sats which are all initially controlled by miners, but miners won’t be incentivized to immediately claim a symbol, but rather resell the rare sats for its additive potential to unlock short symbols.

**Comment by casey** [comment]
The issue I see with that is that it requires running a full sat index in order to tell whether or not an etching of a new rune is valid. The sat index is super heavy, so we don't want to make it a requirement of the protocol.

**Comment by summraznboi** [comment]
I noticed that you were considering linking rune to parent inscription at #69, wouldn’t that also necessitate needing a full ordinals index to ensure validity? Unless an etching is valid regardless if the parent inscription exists or not.

Also, current size of rare sats is under a million currently, if that is too heavy, it could only consider rare and up, which reduces the number of sats tracked less than 3500, just food for thought. (Personally I like rare sats just to reduce the number of actual sats potentially burned, just for preserving higher granularity to max supply).

**Comment by casey** [comment]
You're right that only tracking rare sats would be faster and require less space. However, it still requires the code in the sat index, which is quite complicated. My thought is that if you don't have the inscription index, you just don't display the parent inscription, which is fine, since it doesn't change anything about the rune. Also, unless you link to an inscription which isn't in the inputs, you only have to parse an inscription out of the etching transaction, which is pretty light weight.

**Comment by casey** [comment]
Burning bitcoin introduces a lot of free variables: decay schedule, initial price per length, and has a more complex implementation.

Requiring the corresponding sat be mined is super slow.

So, I'm thinking of the following schedule: Runes of length 13 and above are always allowed to be etched. The minimum length is decreased by 1 every two difficulty adjustments, or approximately every 4 weeks. It will take 336 days for all runes to be allocated, and by the end, hopefully minters will be sophisticated enough to successfully compete for runes in the mempool

**Comment by summraznboi** [comment]
One fun thing to do would be to celebrate the upcoming halving, we can make the minimum length decrease by one during the halving event, and skip the difficulty adjustment before and after. Then there would be a strong alignment of a new min length and rare rarity on that specific halving block :)
