### ISSUE TITLE
Allocation to output greater than max output should burn all runes in input

### ISSUE THREAD

**Issue by casey** [casey/runestone#78]
This allows for adding something else similar to even/amount-based splits.

**Comment by owenstrevor** [comment]
From Casey: This makes it easier to upgrade Runes in the future. Old clients and new clients will still agree where the Runes are. When you want to do an upgrade, the safe way to do it is so that old clients all the Runes going into a transaction are burned. Future upgradeability hook. Then upgraded Runes will be invisible to old clients.

**Comment by casey** [comment]
Done!
