### ISSUE TITLE
Allow open etching with required sat burn

### ISSUE THREAD

**Issue by casey** [casey/runestone#83]
How to specify exchange rate? Integer rune/sat and sat/rune exchange rates are both pretty coarse at small values, i.e., the difference between 1 rune/sat and 2 runes/sat is pretty large. We could use floats, but it wouldn't be a good idea to make floating point math consensus critical.

**Comment by owenstrevor** [comment]
Is this for issuing a Rune ticker? I think 1 rune/sat is better. Floats are just messy. If 1 sat = $1 in the long-term that's great, it will price out the trash or push it to sidechains/other layers. Alternatively, exchanges could just create a liquidity token (they probably will) which will be worth less than 1 sat and have multiple decimals.

WRT burning, if not mutually exclusive, another cool option is to require paying higher fees to miners instead of burning. Paying Runes to miners, etc. I could see project owners wanting to choose different ways.

Obviously, I'm still against unique tickers as I think it's a frontend problem not a protocol problem. There are way more downsides for adoption and none of the successful protocols use unique names.

**Comment by casey** [comment]
This is actually for open mints, where someone creates a token, and anyone can mint it, provided that they burn some sats proportional to the amount they claim.

**Comment by casey** [comment]
I think this isn't incredibly important, and we can add it later if there turns out to be a compelling use case.

**Comment by cliobitcoinbank** [comment]
I understand why you want to do this, but a permanent burn is very drastic.  You could try a feature that requires users to timelock their bitcoin until a future blockheight, users would be forced to save or stake that bitcoin until the agreed upon blockheight. A lock of 100 years is effectively a lifetime burn but a lock of 10 years is still quite a commitment that will reward bitcoin ownership without destroying the bitcoin.  Being able to issue a rune to users who save bitcoin for a period of time could be a fun mechanic to reward savers and setup "staking" systems.

**Comment by casey** [comment]
This would be optional for each etching, so if people don't like it, they could just not use it.

**Comment by cliobitcoinbank** [comment]
I understand that, I just hate the idea of burning bitcoin, I'd like a more temporary option.  Dont huwt the wittle sats.

**Comment by casey** [comment]
I'm inclined not to do this immediately. This can be an added feature that comes later, and if you want to make a rune expensive, use the fees that must be paid to mint as the "burned" sats, and limit mints to a small amount per transaction.

**Comment by jiedo** [comment]
Burning sat does not necessarily increase the value of the rune, it only increases the cost of acquiring the rune. This is different from making the rune more expensive. The sat is only burned, not attached to the rune.
