### ISSUE TITLE
Consider limiting supply and divisibility

### ISSUE THREAD

**Issue by casey** [casey/runestone#94]
- 0 divisibility or some large fixed divisibility
- some maximum and more sensible supply, like a trillion or something
- always show percentage next to amounts

**Comment by sondotpin** [comment]
seems in your code MAX_DIVISIBILITY = 38

**Comment by casey** [comment]
This is correct. 38 was chosen because it's the number of digits in the maximum value of a u128, which is `170141183460469231731687303715884105728`, so with a divisibility of 38, that would be `1.70141183460469231731687303715884105728`.

**Comment by owenstrevor** [comment]
100M or 1B are very typical supply numbers in tokenomics.

This puts the price/token of 100M - 1B in market cap at $1 to $10.

Promising projects typically want to avoid looking like penny stocks at $0.01.

100M is a good number because then you can mentally calculate the market cap very easily.

0.01 = $1M (like a risky penny stock)
$1 = $100M (a good milestone for a crypto project that's at Series B or C)
